name: PR title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  pr-title:
    uses: fjcloudaiconsulting/.github/.github/workflows/pr-title.yml@v1
